### PR TITLE
22.3 Backend for UserReviews created

### PR DESCRIPTION
**Pull request by HiddenBrilliance**

### CODE REVIEW

**Review by ErinKace — CHANGES_REQUESTED** [review]
I noticed that for some reason review.service.ts and review.spec.ts have swapped contents, and I wonder if that could be part of the reason it's not working as intended. Also, I could be way off on this because my own code isn't working, but I think line 10 in that file:  `private apiUrl = '/api/reviews';` Should be `http://localhost:8080/`

**Review by e-karr — COMMENTED** [review]
I second @ErinKace 's edits! Looks like your review.service.ts and review.service.spec.ts got swapped. then the apiUrl in your review service should include the whole local host url. "http://localhost:8080/api/reviews"

I've been deleting the spec.ts files for some of my components along the way because they cause confusion and we're not using them.

These changes may solve some of your roadblocks!

**Review by e-karr — APPROVED** [review]
Got postman to work and can see my review in the database

**Review by ErinKace — APPROVED** [review]
Got it to work through postman too!

**Pull request merged**
