### PR TITLE
3.5 create view for user login

### PR DESCRIPTION
**Pull request by MindzEyeLove**
Register function and button works(login is not functional yet)

### CODE REVIEW

**Review by e-karr — APPROVED** [review]
I was able to register a user!

**Review by e-karr — CHANGES_REQUESTED** [review]
I see some validation annotations in your User model in Java, but I was able to register a user with just a name and leaving all the other fields blank. I was also able to register a user with just the name and password, but leaving email and verify password blank.

Maybe that is your next step, to add error checking and validations so only complete data is saved to the database?

**Review by ErinKace — APPROVED** [review]
Sorry for the delay approving this! I had to drop my tables again and it worked!

**Review by e-karr — DISMISSED** [review]
Plan for validation to be a separate issue!

**Comment by MindzEyeLove** [comment]
Login function works. Be sure to use a registered user and correct password to login the user of choice. The login/sign up button at the top should update to say "Welcome, (username)" after the user is successfully logged in. And the page should redirect to the main browse homepage

**Review by ErinKace — APPROVED** [review]
Awesome! I was able to register a user, login and logout, and see my username in the button! It also didn't let me in unless I provided the right password.

**Review by e-karr — APPROVED** [review]
I was able to log in and I redirected to the home page!

**Pull request merged**
